#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: create-muvjs-app my-app"
  exit 1;
fi

app=$@

git clone https://github.com/yoyomo/muvjs-example $app
cd $app
git remote rm origin
npm install

echo "Now run:"
echo "  cd $app"
echo "  npm start"